<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>def</string>
		<string>mod</string>
	</array>
	<key>name</key>
	<string>Modula-2</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.modula2</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.modula2</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Reconocimiento de las palabras de inicio.</string>
			<key>match</key>
			<string>\b(PROCEDURE|DEFINITION MODULE|IMPLEMENTATION MODULE|MODULE)\b\s+(\w+(\.\w+)?)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.modula2</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.end.modula2</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Reconocimiento de las palabras de fin.</string>
			<key>match</key>
			<string>\b(END)\b\s+(\w+(\.\w+)?)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.modula2</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.modula2</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Classic Modula-2 (PIM) Pervasive Identifiers.</string>
			<key>match</key>
			<string>\b(ABS|BITSET|BOOLEAN|CAP|CARDINAL|CHAR|CHR|DEC|EXCL|FALSE|FLOAT|HALT|HIGH|INC|INCL|INTEGER|LONGINT|LONGREAL|MAX|MIN|NIL|ODD|ORD|PROC|SIZE|TRUE|TRUNC|VAL)\b</string>
			<key>name</key>
			<string>meta.function.modula2</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Classic Modula-2 (PIM) Reserved Words.</string>
			<key>match</key>
			<string>\b(AND|ARRAY|BEGIN|BY|CASE|CONST|DEFINITION|DIV|DO|ELSE|ELSIF|END|EXIT|EXPORT|FOR|FORWARD|FROM|IF|IMPLEMENTATION|IMPORT|IN|LOOP|MOD|MODULE|NOT|OF|OR|POINTER|PROCEDURE|QUALIFIED|RECORD|REPEAT|RETURN|SET|THEN|TO|TYPE|UNTIL|VAR|WHILE|WITH)\b</string>
			<key>name</key>
			<string>keyword.control.modula2</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#block_comment</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.modula2</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.modula2</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.modula2</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.modula2</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.modula2</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.modula2</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|F|f|ll|LL|ull|ULL)?\b</string>
			<key>name</key>
			<string>constant.numeric.modula2</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\(|\)|\+|-|\*|/|:|;|\.|\^|=|:=|&lt;|&gt;|#)</string>
			<key>name</key>
			<string>variable.parameter.function.modula2</string>
		</dict>
	</array>
    <key>repository</key>
    <dict>
        <key>block_comment</key>
        <dict>
            <key>applyEndPatternLast</key>
            <integer>1</integer>
            <key>begin</key>
            <string>\(\*</string>
            <key>captures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.modula2</string>
                </dict>
            </dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#block_comment</string>
                </dict>
            </array>
            <key>end</key>
            <string>\*\)</string>
            <key>name</key>
            <string>comment.block.modula2.one</string>
        </dict>
    </dict>
	<key>scopeName</key>
	<string>source.modula2</string>
	<key>uuid</key>
	<string>c01a654e-2960-44f2-aeae-5909f5043d35</string>
</dict>
</plist>
